//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeeStoreA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CouponCode
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public System.DateTime ExpiryDate { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public Nullable<int> DiscountPercentage { get; set; }
    }
}
