//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeeStoreA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CartItems = new HashSet<CartItem>();
        }
    
        public int Id { get; set; }

        [Required(ErrorMessage = "A name is required")]
        [MinLength(10,ErrorMessage ="A minimum length of 10 characters is required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "A price is required")]
        [Display(Name = "Price (QAR)")]
        [Range(10, 1000, ErrorMessage = "Price must be at least 1 QAR and at most 1000 QAR")]
        public Nullable<int> Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItem> CartItems { get; set; }
    }
}
