//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VeeStoreA.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.CardCodes = new HashSet<CardCode>();
            this.CartItems = new HashSet<CartItem>();
            this.Ratings = new HashSet<Rating>();
        }
    
        public int Id { get; set; }
        [StringLength(50)]
        [Required(ErrorMessage ="Please enter name of the product")]
        public string Name { get; set; }
        [Range(1,2000,ErrorMessage = "Price must between 1 and 2000")]
        
        public int Price { get; set; }
        public string Description { get; set; }
        public Nullable<int> CategoryId { get; set; }
        [Required(ErrorMessage = "An image name is required")]
        public string ImageName { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardCode> CardCodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CartItem> CartItems { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rating> Ratings { get; set; }
    }
}
